### ISSUE TITLE
No implementation for Squad dataset?

### ISSUE THREAD

**Issue by HyeondeyKim** [jiant-dev/jiant#151] opened 2020-08-24 06:42 UTC
I want to train my model on SQuAD dataset. There is no implementation on Squad on the task lib folder. However, I have noticed that there is implementation for SQuAD in the other parts of codes such as jiant/tasks/evaluate/core.py, and etc..... Will you implement SQuAD dataset or should I do it myself? Is supporting fuctions on evaluation still working?

**Comment by zphang** [comment] 2020-08-24 08:54
SQuAD v1.1 and SQuAD v2 are available as `squad_v1` and `squad_v2`.

**Comment by zphang** [comment] 2020-08-24 08:59
To start, you can use our new data downloading script to download the SQuAD datasets:

```bash
python jiant/scripts/download_data/runscript.py \
    download \
    --tasks squad_v1 \
    --output_path /path/to/tasks/folder
```

**Comment by HyeondeyKim** [comment] 2020-09-02 02:11
RuntimeError: stack expects each tensor to be equal size, but got [128] at entry 0 and [80] at entry 1
I have got this error in both SQuAD_v1 and SQuAD_v2....

**Comment by zphang** [comment] 2020-09-02 05:24
Could you post the full stack trace?

**Comment by HyeondeyKim** [comment] 2020-09-02 05:35
@zphang 
  File "run_multi.py", line 69, in <module>
    main_runscript.run_loop(run_args)
  File "/home/hyeondey/2jiant/jiant/jiant/proj/main/runscript.py", line 171, in run_loop
    metarunner.run_train_loop()
  File "/home/hyeondey/2jiant/jiant/jiant/shared/metarunner.py", line 38, in run_train_loop
    for _ in self.yield_train_step():
  File "/home/hyeondey/2jiant/jiant/jiant/proj/main/metarunner.py", line 107, in yield_train_step
    for train_state in train_iterator:
  File "/home/hyeondey/2jiant/jiant/jiant/proj/main/runner.py", line 75, in run_train_context
    self.run_train_step(
  File "/home/hyeondey/2jiant/jiant/jiant/proj/main/runner.py", line 102, in run_train_step
    batch, batch_metadata = train_dataloader_dict[task_name].pop()
  File "/home/hyeondey/2jiant/jiant/jiant/utils/python/datastructures.py", line 160, in pop
    return next(self.iterator)
  File "/home/hyeondey/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/hyeondey/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/hyeondey/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 35, in fetch
    return self.collate_fn(data)
  File "/home/hyeondey/2jiant/jiant/jiant/tasks/core.py", line 160, in collate_fn
    collated_data_rows = {
  File "/home/hyeondey/2jiant/jiant/jiant/tasks/core.py", line 161, in <dictcomp>
    key: flat_collate_fn([getattr(d, key) for d in data_rows])
  File "/home/hyeondey/2jiant/jiant/jiant/tasks/core.py", line 120, in flat_collate_fn
    return dataloader.default_collate(batch)
  File "/home/hyeondey/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 64, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/home/hyeondey/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [128] at entry 0 and [80] at entry 1

Sure. When I tried it several times, the number is 124, 96 etc... It seems that during the pre-processing, it does not returns same size of tensor, however, how can I modify max_seq_length? SQuAD should required more than 128 tho.

**Comment by zphang** [comment] 2020-09-02 06:12
It looks like there might be an issue with how you tokenize and cached the task data. Try using the following command:

```bash
TASK=squad_v1
MODEL_TYPE=roberta-base  # for example
python jiant/proj/main/tokenize_and_cache.py \
    --task_config_path ${BASE_PATH}/tasks/configs/${TASK}_config.json \
    --model_type ${MODEL_TYPE} \
    --model_tokenizer_path /path/to/tokenizer \
    --output_dir /path/to/output \
    --phases train,val \
    --max_seq_length 384 \
    --smart_truncate
```

**Comment by HyeondeyKim** [comment] 2020-09-03 05:15
@zphang There is another issue on preprocessing when save pre-processed data. Is it same issue with issue #47 ?

I have attached error message:
Reading SQuAD Entries: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 442/442 [00:24<00:00, 18.20it/s]
Tokenizing: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 87599/87599 [09:11<00:00, 158.87it/s]
Traceback (most recent call last):
  File "/home/hyeondey/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hyeondey/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hyeondey/2jiant/jiant/jiant/proj/main/tokenize_and_cache.py", line 214, in <module>
    main(args=RunConfiguration.run_cli_json_prepend())
  File "/home/hyeondey/2jiant/jiant/jiant/proj/main/tokenize_and_cache.py", line 162, in main
    chunk_and_save(
  File "/home/hyeondey/2jiant/jiant/jiant/proj/main/tokenize_and_cache.py", line 56, in chunk_and_save
    full_chunk_and_save(
  File "/home/hyeondey/2jiant/jiant/jiant/proj/main/tokenize_and_cache.py", line 87, in full_chunk_and_save
    dataset, length = preprocessing.smart_truncate(
  File "/home/hyeondey/2jiant/jiant/jiant/proj/main/preprocessing.py", line 43, in smart_truncate
    indexer = datum["data_row"].input_mask.reshape(-1, max_seq_length).max(-2)
ValueError: cannot reshape array of size 176 into shape (384)

**Comment by zphang** [comment] 2020-09-03 16:09
I believe I've reproduced the error. Let me look into a fix.

**Comment by zphang** [comment] 2020-09-03 17:07
I've pushed a fix. Can you pull and try running again? Sorry for the trouble.

**Comment by zphang** [comment] 2020-09-17 17:32
I believe this has been fixed. Closing.

**Closed by zphang** 2020-09-17 17:32 UTC
